#!/usr/bin/perl

# Copyright (c) 2022 Todd T. Fries <todd@fries.net>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

use strict;
use warnings;

use Data::Dumper;
use OpenAI::API;

my $key;
open(K,".key");
chomp($key = <K>);
close(K);

my $openai = OpenAI::API->new( api_key => $key );

my $prompt = "Query? (type 'done.' to end)\n";


my $l;
my $query = "";
print $prompt;
while(1) {
	chomp($l = <STDIN>);
	if (length($l) == 0) {
		last;
	}
	if (! ($l =~ /^done.$/)) {
		$query .= $l."\n";
		next;
	}

	print "Query: ".$query;

	my $response = $openai->completions(
		model => 'text-davinci-003',
		prompt => $query,
		max_tokens => 2048,
		temperature => 0.5,
		top_p => 1,
		frequency_penalty => 0,
		presence_penalty => 0
	);


	print "Response(s):\n";
	if (defined(@{$response->{'choices'}}[0])) {
		foreach my $choice (@{$response->{'choices'}}) {
			printf "%2d. %s\n\n", $choice->{index}, $choice->{text};
		}
		print "Stats: ";
		print $response->{'created'};
		printf " tot/prompt/compl tokens = %d/%d/%d\n",
			$response->{'usage'}->{'total_tokens'},
			$response->{'usage'}->{'prompt_tokens'},
			$response->{'usage'}->{'completion_tokens'};
	} else {
		print Dumper($response);
	}
	print "\n";

	print $prompt;
}
